# ------- apriori paremeters -------
minsup=0.01
minconf=0.6
# ------- hash tree parameters -------
hash_pivot=64
bucket_size=64
# ------- parallel paremeters -------
threads=16
# miminalna ilość elementów w L_k żeby używać wątków zamaist liczyć synchronicznie
min_size=1000
data_path=.\data\dataset.txt